# Gmail to SQLite Configuration
# This file contains the core configuration for gmail-to-sqlite
# Note: DATA_DIR and API keys are configured in .secrets.toml for security
# Application settings
DEBUG = false
MAX_WORKERS = 4
BATCH_SIZE = 100
